"""Capa de retrocompatibilidad: opt_pyFE ahora es trading_unam."""

from trading_unam import (
    __author__,
    __email__,
    __version__,
    descargar_datos,
    getdata,
    get_data,
    calcular_rendimientos_log,
    proyeccion,
    bandas_bollinger,
    bollinger_bands,
    simular_portafolios,
    simulate_portfolios,
    encontrar_mejor_portafolio,
    encontrar_minima_varianza,
    mostrar_resultados,
    desempeno,
    portfolio_performance,
    ejecutar_analisis,
    historical_var,
    historicalVar,
    historical_cvar,
    historicalCVar,
    monte_carlo_sim,
    MonteCarlo,
    mc_var,
    mcVaR,
    mc_cvar,
    mcCVaR,
    resumen_riesgo,
    resum,
    analizar_sentimiento,
    analyze_sentiment,
    __all__,
)
